[book]
authors = ["Oliver Nordbjerg", "Codingsh"]
language = "pt-br"
multilingual = false
src = "src"
title = "Livro Foundry"
description = "Um livro sobre tudo sobre Foundry"

[output.html]
git-repository-url = "https://github.com/foundry-rs/book"
edit-url-template = "https://github.com/foundry-rs/book/edit/master/{path}"
default-theme = "ayu"
additional-js = ["src/static/solidity.min.js"]
cname = "book.getfoundry.sh"
no-section-label = true
additional-css = ["src/static/custom.css"]

[output.html.fold]
enable = true
level = 1
